### ISSUE TITLE
More details on pretraining of SLATE for Reaching task.

### ISSUE THREAD

**Issue by ugadiarov-la-phystech-edu** [jsikyoon/OCRL#1]
Hello. I am trying to reproduce the reported results in CausalWorld environment. Is my understaning correct that the provided pretrained SLATE model (pretrained_encoders/slate.pth) was trained for 2D tasks, but not for 3D Object Reaching Task? If so, can you please provide more details on pretraining SLATE model:

- How many observations it is necessary to collect for a dataset in order to train SLATE for Reaching task?
- Did you use the same values for hyperparameters as for 2D tasks (learning rates, number of epochs, and so on)?

**Comment by jsikyoon** [comment]
Hi Ugadiarov, thank you for your interest in our project.

I asked what you said to my colleague who worked in 3D experiments. It looks like he is in travel yet, I will share the update when he does. 

I appreciate your patience in advance.

Bests, Jaesik.

**Comment by jsikyoon** [comment]
We shared the pretrained SLATE for CausalWorld environment in [link](https://www.dropbox.com/scl/fi/g6fwc8gqdp7gj5s1nthkq/slate_3d.pth?rlkey=psr7maq0f8c4sd2b909x9fi3j&dl=0).

The running script to take for the RL task on the CausalWorld environment is also updated in [132fa82](https://github.com/jsikyoon/OCRL/commit/132fa82d8d1e45fe1fbe7b2914bc4525755163f8).

I'll close it. If there were other questions, please feel free to let us know.

@yfw helped to cover this issue. Thank you!

Bests, Jaesik.

**Comment by dido1998** [comment]
Hello @jsikyoon is it possible to release the dataset for the causalworld task too?

**Comment by jsikyoon** [comment]
We updated the dataset `CwTargetEnv-N4C11S1S1-Tr1000000-Val10000.hdf5` in the shared folder for the dataset.

@yfw thank you!

Bests, Jaesik.

**Comment by dido1998** [comment]
@jsikyoon I can see only one dataset on this link https://www.dropbox.com/sh/hr3hg73ybrraftm/AAC0gboOP3o2qrzYrrELV4vQa/datasets?dl=0&subfolder_nav_tracking=1. Could you share the link of the location where you added the file?

**Comment by jsikyoon** [comment]
I gave a permission on the file for everyone. How about now?

**Comment by dido1998** [comment]
It still shows only one file 
<img width="968" alt="image" src="https://github.com/jsikyoon/OCRL/assets/20562351/da78b3d9-e372-420a-ad5f-cb2f2a6917a4">

**Comment by jsikyoon** [comment]
<img width="491" alt="image" src="https://github.com/jsikyoon/OCRL/assets/22428579/93cdfd33-71f0-4069-9792-8c68b59f76f1">
I checked there are two files. Could you check again?

**Comment by dido1998** [comment]
It still shows same to me. Just for sanity check, [this](https://www.dropbox.com/sh/hr3hg73ybrraftm/AAC0gboOP3o2qrzYrrELV4vQa/datasets?dl=0&subfolder_nav_tracking=1) is the link right?

**Comment by jsikyoon** [comment]
Ah no, the folder link is updated after adding the file. I didn't catch it.

Sorry for your inconvenience.

[This](https://www.dropbox.com/scl/fo/7e7iluev754rk2cpw7bmq/h?rlkey=3wmse4davpy147wwta5mgjoyb&dl=0) is a new link. I will update my document also.

**Comment by dido1998** [comment]
No worries! Thanks for the help, I can access it now
