### ISSUE TITLE
OOD Evaluations

### ISSUE THREAD

**Issue by dido1998** [jsikyoon/OCRL#2]
Can you provide some instructions on running the OOD evaluations from the paper?

**Comment by jsikyoon** [comment]
You can check it on the uncleaned version of this codebase, but I am not sure it is running on a cleaned codebase.

https://github.com/jsikyoon/OCRL/blob/29fdd2c0ea20fffe7a54b05f27fed60e25c25128/ood_test_sb3s.py

Bests, Jaesik.
