### ISSUE TITLE
Question regarding collect_dataset_from_cw_envs.py

### ISSUE THREAD

**Issue by EwertzJN** [jsikyoon/OCRL#4]
Hi, I have a question regarding the script ([collect_dataset_from_cw_envs.py](https://github.com/jsikyoon/OCRL/blob/main/envs/collect_dataset_from_cw_envs.py)) which I thought was used to generate the pretraining data for the Causalworld environment. What I observe is that when I generate data with the script, I get images of the environment from 3 different angles. I am wondering about this, because after analyzing the data of the data set provided on the Dropbox ([CwTargetEnv-N4C11S1S1-Tr1000000-Val10000.hdf5](https://www.dropbox.com/scl/fo/7e7iluev754rk2cpw7bmq/h/CwTargetEnv-N4C11S1S1-Tr1000000-Val10000.hdf5?rlkey=3wmse4davpy147wwta5mgjoyb&dl=0)), it seems to me that there are only observations from one angle in this data set. And from the angle that is also shown in the publication ([An Investigation into Pre-Training Object-Centric Representations for Reinforcement Learning](https://arxiv.org/pdf/2302.04419.pdf)). I hope my confusion can be resolved, perhaps by giving me the script used to create the dataset uploaded to the Dropbox. Many thanks in advance.

**Comment by jsikyoon** [comment]
Thank you for your interesting for our project.

I think it can be answered by @yfw. @yfw, can you care this question?

Bests, Jaesik.

**Comment by yfw** [comment]
For pre-training on the CausalWorld environment, we used this config file: https://github.com/jsikyoon/OCRL/blob/main/configs/env/cw-notarget-N4C11S1S1-hard.yaml. You should be able to run [collect_dataset_from_cw_envs.py](https://github.com/jsikyoon/OCRL/blob/main/envs/collect_dataset_from_cw_envs.py) with `--config-name=cw-notarget-N4C11S1S1-hard` to recreate it. Hope that helps and sorry for the confusion!

**Comment by jsikyoon** [comment]
Hi @EwertzJN , 

I will close this issue. If you have additional questions, please feel free to reopen this issue or create a new issue.

Thank you for your interesting.

**Comment by EwertzJN** [comment]
Thank you very much for your help.
I just have one small question: In the script (collect_dataset_from_cw_envs.py) it looks as if the first observation after the environment has been reset is always thrown away, i.e. it is not included in the data set. Why is this the case?

**Comment by yfw** [comment]
I'm not sure if there was a great reason for this, but I don't think it should have much effect on the resulting dataset.

**Comment by EwertzJN** [comment]
I have one more question and I hope it's okay to ask it briefly here in this issue. I'm wondering which configuration of the 3D environment was used to perform reinforcement learning.

**Comment by yfw** [comment]
We used the cw-target-N4C4S1S1-hard configuration (https://github.com/jsikyoon/OCRL/blob/main/configs/env/cw-target-N4C4S1S1-hard.yaml).
